--
-- File generated with SQLiteStudio v3.0.6 on Mon Aug 24 14:10:55 2015
--
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: wonders
CREATE TABLE wonders (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR (0) NOT NULL, description TEXT NOT NULL, url VARCHAR (0), photo VARCHAR (0), latitude DOUBLE DEFAULT (0), longitude DOUBLE DEFAULT (0));
INSERT INTO wonders (id, name, description, url, photo, latitude, longitude) VALUES (1, 'Pirâmide de Quéops', 'Ao contrário do que muitos pensam é apenas a Pirâmide de Quéops (e não todas as três grandes Pirâmides de Gizé) que faz parte da lista original das Sete Maravilhas do Mundo.

A Pirâmide de Quéops foi construída há mais de 4500 anos, por volta do ano 2550 a.C., e é também chamada de Grande Pirâmide de Gizé ou apenas Grande Pirâmide. A majestosa construção de 147 metros de altura foi a maior construção feita pelohomem durante mais de quatro mil anos, sendo superada apenas no final do século XIX (precisamente em 1889), com a construção da Torre Eiffel.

A Grande Pirâmide de Gizé foi construída como tumba real para o faraó Khufu/Quéops (que dá nome à pirâmide). O curioso é que a pirâmide de Quéops já era a mais antiga dentre todas as maravilhas do mundo antigo (afinal, na época já fazia mais de dois mil anos que havia sido construída) e é justamente a única que se mantém até hoje.', 'https://pt.wikipedia.org/wiki/Pir%C3%A2mide_de_Qu%C3%A9ops', 'piramida_cheopsa.jpg', 29.9792, 31.1342);
INSERT INTO wonders (id, name, description, url, photo, latitude, longitude) VALUES (2, 'Estátua de Zeus em Olímpia', 'A estátua de Zeus em Olímpia foi construída no século V a.C. por Fídias, em homenagem ao rei dos deuses gregos — Zeus. Aestátua, construída em ouro e marfim e decorada com pedras preciosas, possuía 12 metros de altura. Após 800 anos foi levada para Constantinopla (hoje Istambul), onde acredita-se ter sido destruída em 462 d.C. por um terremoto.

Essa é considerada sua obra-prima. Tanto os gregos amavam seus trabalhos que dizia-se que ele revelava aos homens a imagem dos deuses. Supõe-se que a construção da estátua tenha levado cerca de oito anos. Zeus (Júpiter, para os romanos) era o senhor do Olimpo, a morada das divindades. A estátua media de 12 a 15 metros de altura - o equivalente a um prédio de cinco andares - e era toda de marfim e ébano. Seus olhos eram pedras preciosas.

Fídias esculpiu Zeus sentado num trono. Na mão direita levava a estatueta de Nice, deusa da Vitória; na esquerda, uma esfera sob a qual se debruçava uma águia. Supõe-se que, como em representações de outros artistas, o Zeus de Fídias também mostrasse o cenho franzido. A lenda dizia que quando Zeus franzia a fronte o Olimpo todo tremia. Quando a estátua foi construída, a rivalidade entre Atenas e Esparta pela hegemonia no Mediterrâneo e na Grécia continental mergulhou os gregos numa sucessão de guerras. Os combates, no entanto, não prejudicaram as realizações culturais e artísticas da época. Ao contrário, o século V a.C. ficou conhecido como o século de ouro na história grega devido ao extraordinário florescimento da arquitetura, escultura e outras artes.
', 'https://pt.wikipedia.org/wiki/Est%C3%A1tua_de_Zeus_em_Ol%C3%ADmpia', 'zeus.jpg', 0, 0);
INSERT INTO wonders (id, name, description, url, photo, latitude, longitude) VALUES (3, 'Jardins suspensos da Babilônia', 'Os Jardins Suspensos da Babilônia são as maravilhas menos conhecidas, já que até hoje encontram-se poucos relatos e nenhum sítio arqueológico foi encontrado com qualquer vestígio do monumento. O único que pode ser considerado "suspeito" é um poço fora dos padrões que imagina-se ter sido usado para bombear água. Foram construídos por volta de 600 a.C., às margens do rio Eufrates, na Mesopotâmia - no atual sul do Iraque. Os jardins, na verdade, eram seis montanhas artificiais feitas de tijolos de barro cozido - conhecidos como zigurates - com terraços sobrepostos onde foram plantadas árvores e flores. Calcula-se que estivessem apoiados em colunas cuja altura variava de 25 a 100 metros. Para se chegar aos terraços subia-se por uma escada de mármore; entre as folhagens havia mesas e fontes. Os jardins ficavam próximos ao palácio do reiNabucodonosor II, que os teria mandado construir em homenagem à mulher, Amitis, saudosa das montanhas do lugar onde nascera.

Capital do império caldeu, a Babilônia, sob Nabucodonosor, tornou-se a cidade mais rica do mundo antigo. Vivia do comércio e da navegação, buscando produtos na Arábia e na Índia e exportando lã, cevada e tecidos. Como não dispunham de pedras, os babilônios usavam em suas construções tijolos de barro cozido e azulejos esmaltados. No século V a.C., Heródoto dizia que a Babilônia "ultrapassava em esplendor qualquer cidade do mundo conhecido". Mas em 539 a.C. o império caldeu foi conquistado pelos persas e dois séculos mais tarde passou a ser dominado por Alexandre, o Grande, tornando-se parte da civilização helenística. Depois da morte de Alexandre (323 a.C.), a Babilônia deixou de ser a capital do império. Começou assim sua decadência. Não se sabe quando os jardins foram destruídos; sobre as ruínas da Babilônia ergueu-se, hoje, a cidade de Al-Hillah, a 160 quilômetros de Bagdá, a capital do Iraque.
', 'https://pt.wikipedia.org/wiki/Jardins_suspensos_da_Babil%C3%B4nia', 'jardins_suspensos.jpg', 32.5436, 44.4241);
INSERT INTO wonders (id, name, description, url, photo, latitude, longitude) VALUES (4, 'Templo de Ártemis em Éfeso', 'O templo de Ártemis em Éfeso, construído para a deusa grega da caça e protetora dos animais selvagens, foi o maior templo do mundo antigo. Localizado em Éfeso, atual Turquia, o templo foi construído em 550 a.C. pelo arquiteto cretense Quersifrão e por seu filho, Metagenes. Após concluído virou atração turística com visitantes de diversos lugares entregando oferendas, e foi destruído em 356 a.C. por Heróstrato, que acreditava que destruindo o templo de Ártemis teria seu nome espalhado por todo o mundo. Sabendo disso, os habitantes da cidade não revelaram seu nome, só conhecido graças ao historiador Estrabão. 

Alexandre ofereceu-se para restaurar o templo, mas ele começou a ser reconstruído só em 323 a.C., ano da morte do macedônio. Mesmo assim, em 262 d.C., ele foi novamente destruído, desta vez por um ataque dos godos. Com a conversão dos cidadãos da região e do mundo ao cristianismo, o templo foi perdendo importância e veio abaixo em 401 d.C; e hoje existe apenas um pilar da construção original em suas ruínas.', 'https://pt.wikipedia.org/wiki/Templo_de_%C3%81rtemis_em_%C3%89feso', 'templo_artemis.jpg', 37.9503, 27.3658);
INSERT INTO wonders (id, name, description, url, photo, latitude, longitude) VALUES (5, 'Mausoléu de Halicarnasso', 'O Mausoléu de Halicarnasso foi o suntuoso túmulo que a sátrapa da Cária Artemísia II mandou construir sobre os restos mortais de seu irmão e marido, Mausolo, em 353 a.C.. A estrutura foi desenhada pelos arquitetos gregos Sátiro e Pítis. Ela tinha aproximadamente 45 metros de altura, e cada um de seus quatro lados foi adornado com relevos criados por cada um dos quatro escultores gregos — Briáxis, Escopas de Paros, Leocarés e Timóteo.

Foi construído por dois arquitetos gregos — Sátiro e Pítis — e por quatro escultores gregos — Briáxis, Escopas, Leocarés eTimóteo. A tumba foi erigida em uma colina tendo uma vista panorâmica da cidade. A estrutura ficava em um pátio fechado, em cujo centro estava uma plataforma com a tumba. Uma escada, ladeada por estátuas de leões de pedra, levava ao topo da plataforma. Ao longo da parede exterior desta ficavam muitas estátuas descrevendo deuses e deusas. Em cada canto, guerreiros de pedra cavalgando guardavam a tumba. No centro da plataforma estava a tumba propriamente dita. Feita principalmente de mármore, era um bloco quadrado de um terço da altura de 45 metros do mausoléu. Esta seção era coberta de esculturas em relevo exibindo cenas de ação da mitologia e história grega. Uma parte exibia a Centauromaquia, batalha doscentauros com os Lápitas; outra, gregos em luta com as amazonas, uma raça de mulheres guerreiras. Hoje, os fragmentos desse monumento são encontrados noMuseu Britânico, em Londres, e em Bodrum, na Turquia. A palavra mausoléu é derivada de mausoleum, o nome em latim do monumento.
', 'https://pt.wikipedia.org/wiki/Mausol%C3%A9u_de_Halicarnasso', 'mausoleu.jpg', 37.0381, 27.4244);
INSERT INTO wonders (id, name, description, url, photo, latitude, longitude) VALUES (6, 'Colosso de Rodes', 'O Colosso de Rodes era uma gigantesca estátua do deus grego Apolo colocada na entrada marítima da ilha grega de Rodes. Ela foi finalizada em 280 a.C. pelo escultor Carés de Lindos, tendo 30 metros de altura e setenta toneladas de bronze, de modo que qualquerbarco que adentrasse a ilha passaria entre suas pernas, que possuía um pé em cada margem do canal que levava ao porto. Na suamão direita havia um farol que guiava as embarcações à noite.

Era uma estátua tão imponente que um homem de estatura normal não conseguia abraçar o seu polegar. Foi construída para comemorar a retirada das tropas macedônias que tentavam conquistar a ilha, e o material utilizado para sua confecção foram armas abandonadas pelos macedônios no lugar.

Apesar de imponente, ficou em pé durante apenas 55 anos, sendo abalada por um terremoto que a jogou no fundo da baía. Ptolomeu IIIse ofereceu para reconstruí-la, mas os habitantes da ilha recusaram por achar que haviam ofendido Hélio. E no fundo do mar ainda era tão impressionante que muitos viajaram para vê-la lá em baixo, onde foi esquecida até a chegada dos árabes, que a venderam como sucata.
', 'https://pt.wikipedia.org/wiki/Colosso_de_Rodes', 'colosso_rodes.jpg', 36.4442, 28.2142);
INSERT INTO wonders (id, name, description, url, photo, latitude, longitude) VALUES (7, 'Farol de Alexandria', 'O Farol de Alexandria foi construído a mando de Ptolomeu I no ano 280 a.C. pelo arquiteto e engenheiro grego Sóstrato de Cnido.

Sobre uma base quadrada erguia-se a esbelta torre octogonal de mármore, com uma altura que variava entre 115 e 150 metros de altura, que por mais de cinco séculos manteve-se entre as mais altas estruturas feitas pelo homem.

Em seu interior ardia uma chama que, através de espelhos, iluminava a uma distância de até 50 quilômetros.

À excepção das pirâmides de Gizé, foi a que mais tempo durou entre as outras maravilhas do mundo, sendo destruída por umterremoto em 1375. Suas ruínas foram encontradas em 1994 por mergulhadores.
', 'https://pt.wikipedia.org/wiki/Farol_de_Alexandria', 'farol_alexandria.jpg', 0, 0);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
